console.log("***********Step1**************");

var sweety = "sweety";
var cutie = "cutie";
console.log("before swapping variable ",sweety, cutie);
var temp = sweety;
sweety = cutie;
cutie = temp;
console.log("After swapping variable");
console.log(sweety, cutie);
console.log("************step2*******************8");
var num1 = 100;
var num2 = 200;
var num3 = 300;
console.log("before swapping variable ",num1, num2, num3);
var temp = 100;
num1 = num2;
num2 = num3;
num3 = temp;
console.log("After swapping variable",num1, num2, num3);