console.log("*********step1********");
var bankName;
bankName = "SBI Bank";
console.log("Type of bankname is:",bankName);
console.log("*********step2********");
var marks = "90%";
console.log("type of marks is:", typeof marks);
console.log("**********Step3**************");
var isWorking = true;
console.log("type of isWorking is:",typeof isWorking);
console.log("**************Step4************");
var totalCount = "Hundred and Seven";
console.log("type of totalCount is:",typeof totalCount);
totalCount = 107;
console.log("value of totalCount is:",totalCount);
console.log("type of totalCount is:",typeof totalCount);